[settings]
ui_bg = "#1f1f1f"
ui_fg = "white"
text_bg = "#2d2d2d"
text_fg = "white"
text_font = "Segoe UI"
font_size = 11
wrap = "True"
zoom_in = "<Control-plus>"
zoom_out = "<Control-minus>"
max_undo_steps = 500
max_redo_steps = 40
autosave_interval_sec = 120
navigation_buttons = "True"
use_tab_colours = "True"
text_active_bg = "#c8102e"
text_active_fg = "white"
selection_bg = "#c8102e"
selection_fg = "white"
cursor_colour = "white"
tab_0_colour = "red"
tab_1_colour = "green"
tab_2_colour = "blue"
regular_font = "Segoe UI"
bold_font = "Segoe UI Bold"
light_font = "Segoe UI Light"
medium_font = "Segoe UI Semibold"
thin_font = "Segoe UI Semilight"
security_button_name = "Security"
security_documents_name = "Security Documents"
security_folder = "S:/Your/security/docs/folder"
file_options_folder = "C:/Your/docs/folder"
use_file_menu = "True"
use_file_backup = "True"
use_spell_checking = "True"
spell_check_languages = "['en']"
spell_check_typing_range = "line"
use_typing_language_to_spell_check = "True"
spell_check_when_opening_file = "False"
spell_check_colour = "red"
backup_folder_path = "C:/Your/backup/folder"
secure_backup_folder_path = "S:/Your/security/backup/folder"
auto_quotes = "True"
get_title_from_text = "True"
info_labels_timer = "False"
auto_secure_at_sf = "True"
auto_secure_at_sd = "True"
text_gaps = "True"
show_full_paths = "False"
reopen_after_exit = "True"
default_autosave = "True"
default_metadata = "True"
default_backup = "True"
default_spell_check = "False"
new_window_when_opening = "False"
cmd_mount_drive = 'your cmd command to mount the security drive'
cmd_mount_drive_success_pattern = 'your regex pattern to check if the drive was mounted successfully'
cmd_dismount_drive = 'your cmd command to dismount the security drive'
cmd_test_mount_status = 'your cmd command to check if the drive is mounted (this will only be used before dismounting and mounting, for other non critical operations the script checks using os.path.exists)'
cmd_test_mount_status_success_pattern = 'your regex pattern to check if the drive is mounted based on the response from cmd_test_mount_status'